[project]
name = "package-supplychain-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastexcel>=0.16.0",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "loguru>=0.7.3",
    "openpyxl>=3.1.5",
    "polars-lts-cpu==1.31.0",
    "pyarrow>=22.0.0",
    "pyinstaller>=6.17.0",
    "requests>=2.32.5",
    "unidecode>=1.4.0",
]
